import time
import uuid
import os
from pptx import Presentation
from sqlalchemy.orm import Session
from .. import models
from ..config import settings
from ..database import SessionLocal

# Simple mock for PPT generation
def create_demo_ppt(project: models.Project, output_path: str):
    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = f"{project.title} Presentation"
    slide.placeholders[1].text = "Generated by ProjectPilot AI\n(Demo Mode)"
    
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    slide2.shapes.title.text = "Abstract & Ideas"
    slide2.placeholders[1].text = "Here are the key points we extracted: \n- AI is cool \n- SaaS drives revenue \n- Students love automation"

    prs.save(output_path)
    return output_path

# Main background processing function
def process_report_task(task_id: str, project_id: str):
    # Retrieve a new session since we're in a background thread
    db: Session = SessionLocal()
    try:
        # Get the report tied to this task
        report = db.query(models.Report).filter(models.Report.task_id == task_id).first()
        if not report:
            return
            
        report.status = models.TaskStatus.processing.value
        db.commit()
        
        project = db.query(models.Project).filter(models.Project.id == project_id).first()
        
        # Simulate processing time
        time.sleep(3)
        
        # DEMO MODE Logic 
        if settings.DEMO_MODE or not settings.OPENAI_API_KEY:
            report.abstract = "This is a demo abstract. Plagiarism is detected at 5%."
            report.introduction = "This project aims to automate student academic work."
            report.methodology = "Using FastAPI, React, and Terraform."
            report.results = "Successfully processed 1M tokens per second."
            report.conclusion = "The system is robust and scalable."
            report.plagiarism_score = 12.5
            report.similar_projects = "['Project A', 'Dataset B']"
            report.key_points = '["Fast execution", "High modularity"]'
            report.viva_questions = '["What is React?", "How do you scale PostgreSQL?"]'
            
            # Generate real PPTX
            ppt_filename = f"{uuid.uuid4()}.pptx"
            ppt_path = os.path.join(settings.LOCAL_UPLOAD_DIR, ppt_filename)
            create_demo_ppt(project, ppt_path)
            
            # Store mock URL for PPT
            report.ppt_url = f"/uploads/{ppt_filename}"
            
        else:
            # Here you would actually call OpenAI
            # openai.Completion.create(...)
            pass
        
        report.status = models.TaskStatus.completed.value
        db.commit()
        
    except Exception as e:
        db.rollback()
        report = db.query(models.Report).filter(models.Report.task_id == task_id).first()
        if report:
            report.status = models.TaskStatus.failed.value
            db.commit()
    finally:
        db.close()
